### ISSUE TITLE
ipad mini3 error

### ISSUE THREAD

**Issue by jjunghyup** [nanoscopic/h264_to_jpeg#1]
https://github.com/nanoscopic/h264_to_jpeg/blob/3e64b68b63e98e65973ef5e854cec6284c647ade/hw_decode.c#L167

When running on ipad mini 3 version, the following error occurs. How can I know how to fix it?

```
Receiving data from nanomsg tcp://127.0.0.1:7878
Send data to nanomsg tcp://127.0.0.1:7879
Fetching headers to start decoder
nalu type: SPS, size: 19
nalu type: PPS, size: 8
nalu type: SEI, size: 29
Opening Input
Input Open
Fetching first frame to initialize decoder
 Iframe - size: 26128
Finding stream info
[h264 @ 0x7fe99d006e00] concealing 5025 DC, 5025 AC, 5025 MV errors in I frame
[h264 @ 0x7fe99b001800] decoding for stream 0 failed
Finding best stream
Getting hardware config
Initiating decoder
Decoder is started; beginning loop reading frames
Time from start of main till video loop: 51234.434000
 Iframe - size: 24172 - Timediff:15.360000
Source dimensions 1200 x 1600
Target dimensions 600 x 800
[h264 @ 0x7fe99a800000] hardware accelerator failed to decode picture
Error during decoding: Unknown error occurred
Bus error: 10
```

**Comment by jjunghyup** [comment]
I looked into the cause more, but the problem seems to be that ipadmini is sending an audio packet, and I think the error may have occurred by interpreting the packet with the video "avcodec_send_packet(avctx, packet)" analyzer.

```
{"level":"debug","msg":"Rcv:SYNC_AFMT{ClockRef:1005b7248, CorrelationID:1005289d0, AudioStreamBasicDescription:{SampleRate:48000.000000,FormatFlags:76,BytesPerPacket:4,FramesPerPacket:1,BytesPerFrame:4,ChannelsPerFrame:2,BitsPerChannel:16,Reserved:0}}","time":"2020-06-03T09:37:48+09:00"}
{"level":"debug","msg":"Send AFMT-REPLY {correlation:1005289d0}","time":"2020-06-03T09:37:48+09:00"}
```

**Comment by nanoscopic** [comment]
@jjunghyup 
Your initial response before editing was interesting in that the UDID output for your device was followed by gibberish. `\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000`

You are the second user to report that ios_video_pull is outputting the null characters that way. In your case it still seems to work ( at least partially ) and only have a corrupt output. That still is a bug and I'll open a bug for that on the quicktime_video_hack repo.

The idea that it is attempting to process an audio packet is certainly possible. I can attempt to diagnose the issue if you could capture a file containing the video stream.

Use `./bin/ios_video_pull -pull -file [filename]` to save a chunk of data from your device. Press control see after a second or two so it isn't too large.

You can then feed it into h264_to_jpeg using `./bin/decode file --file [filename]`. Do that and verify that it still encounters the same/similar error. Once you have a file that generates that error you can post that file and I can look at its contents to diagnose what is going on and why h264_to_jpeg cannot process it.

**Comment by jjunghyup** [comment]
same error on `./bin/decode file --file [filename]`
here is testfile.

please check it

[abc.zip](https://github.com/nanoscopic/h264_to_jpeg/files/4720541/abc.zip)

**Comment by nanoscopic** [comment]
If you `brew install ffmpeg` you can then also use `ffplay abc` to play the file directly to confirm it is valid video that can be decoded by ffmpeg.

I just did that and the video is able to be decoded by ffmpeg. It still spits out an error though "error while decoded MB 44 82, bytestream -6". I will investigate further and see if I can figure out what the issue is.

**Comment by jjunghyup** [comment]
Are you sure that the file I attached plays well?

I've done it with `ffplay abc`, but the video is playing and I got the same error at the end.

```
chajunghyeob-XXXXX-SWgisulLab:ios_video_pull latte$ ffplay abc
ffplay version 4.2.3 Copyright (c) 2003-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.3 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags=-fno-stack-check --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, h264, from 'abc':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, progressive), 1200x1600, 25 fps, 25 tbr, 1200k tbn, 50 tbc
[swscaler @ 0x113a86000] deprecated pixel format used, make sure you did set range correctly
[h264 @ 0x7fee1e82a400] error while decoding MB 70 75, bytestream -6

```

**Comment by nanoscopic** [comment]
Initial thoughts: It appears that, for your device ( I am guessing for all ipad mini of that specific hardware / software combination ) the video stream cannot be decoded properly by the hardware acceleration setup of ffmpeg. The software variant ( ffplay for example ) is capable of decoding it, but seems to recognize some corruption in the stream.

That corruption could be due to how the video stream is created on the device, or it could be to some issue with qvh.

Another thing that can be done to analyze the output it to use h264_analyze.

If you `brew install h264bitstream` you can then run `h264_analyze abc` to show the nalu information for every nalu present in the file.

A more shortened output that makes a bit more sense is `h264_analyze abc | grep -e "unit_type\|frame_num" | less` That will give you a less session, where you can page up and down and see the types of nalus present in the file.

Looking at that; it looks fine as far as the nalu types present in the file. It is a bit strange to me that there are multiple type=5 ( iframe ) at the start of each second of video. It appears that what is going on is that the iframes are split into multiple slices ( see the "first_mb_in_slice" on the repeated type: 5 nalus ).

Here is an example from your sample file:
```
!! Found NAL at offset 2154204 (0x20DEDC), size 200865 (0x310A1)
0.8: forbidden_zero_bit: 0
0.7: nal->nal_ref_idc: 1
0.5: nal->nal_unit_type: 5
1.8: sh->first_mb_in_slice: 0
1.7: sh->slice_type: 2
1.4: sh->pic_parameter_set_id: 0
1.3: sh->frame_num: 0
2.6: sh->idr_pic_id: 0
2.5: sh->pic_order_cnt_lsb: 0
3.7: sh->drpm.no_output_of_prior_pics_flag: 0
3.6: sh->drpm.long_term_reference_flag: 0
3.5: sh->slice_qp_delta: -7
4.6: sh->disable_deblocking_filter_idc: 2
4.3: sh->slice_alpha_c0_offset_div2: 0
4.2: sh->slice_beta_offset_div2: 0
!! Found NAL at offset 2355073 (0x23EF81), size 233140 (0x38EB4)
0.8: forbidden_zero_bit: 0
0.7: nal->nal_ref_idc: 1
0.5: nal->nal_unit_type: 5
1.8: sh->first_mb_in_slice: 2475
3.1: sh->slice_type: 2
4.6: sh->pic_parameter_set_id: 0
4.5: sh->frame_num: 0
5.8: sh->idr_pic_id: 0
5.7: sh->pic_order_cnt_lsb: 0
5.1: sh->drpm.no_output_of_prior_pics_flag: 0
6.8: sh->drpm.long_term_reference_flag: 0
6.7: sh->slice_qp_delta: -7
7.8: sh->disable_deblocking_filter_idc: 2
7.5: sh->slice_alpha_c0_offset_div2: 0
7.4: sh->slice_beta_offset_div2: 0
```

My guess as to what is going on is that for that device, it is sending frames split up into pieces, and that the hardware encoder needs those pieces reassembled into single larger nalus to function properly.

There are two options here:
1. Reconfigure h264_to_jpeg to provide a software decoding option. This option, while it will consume more CPU power, should work. The question is if it will be able to keep up with the constant video stream. I'm not sure. It would need to be tested.
2. Learn more about the split up slices, and how to reassemble them into larger nalus before feeding them into the hardware decoder. This is more work than #1 but would be optimal. It is also speculation here. I think that would fix it but I couldn't be sure till trying it.

Could you share what exact hardware model and IOS version your Ipad Mini is?

**Comment by nanoscopic** [comment]
There is a 3rd option I think. When I wrote h264_to_jpeg I assumed none of the frames are split up, so only a single NALU is pulled in for an iframe. In this case multiple NALUs form a single frame. If I just receive all the NALUs that go together and send them all into the hardware decoder it may work as well.

**Comment by nanoscopic** [comment]
When I use `ffplay` the video does play on my screen, yes. It outputs errors as well but I believe it is still correctly displaying the video contained in the file. I don't understand the details of the errors but hopefully those are irrelevant to why it doesn't "work"

**Comment by jjunghyup** [comment]
> Could you share what exact hardware model and IOS version your Ipad Mini is?

my ipad mini model is `ModelNumber: MGHV2`

and here is detail info 
```
chajunghyeob-XXXXX-SWgisulLab:ios_video_pull latte$ ideviceinfo
ActivationState: Activated
ActivationStateAcknowledged: true
BasebandActivationTicketVersion: V2
BasebandCertId: 3554301762
BasebandChipID: 7282913
BasebandKeyHashInformation: 
 AKeyStatus: 2
 SKeyHash: 7MQEUyvzG4gjjZc7KsNNAVTS8g4=
 SKeyStatus: 0
BasebandMasterKeyHash: AEA5CCE143668D0EFB4CE1F2C94C966A6496C6AA
BasebandRegionSKU: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
BasebandSerialNumber: FMgOcA==
BasebandStatus: BBInfoAvailable
BasebandVersion: 8.30.01
BluetoothAddress: 6c:94:f8:c6:88:35
BoardId: 52
BrickState: false
BuildVersion: 15C202
CPUArchitecture: arm64
CarrierBundleInfoArray[0]: 
CertID: 3554301762
ChipID: 35168
ChipSerialNo: XXXXXXX
DeviceClass: iPad
DeviceColor: #3b3b3c
DeviceName: XXXXXXX iPad
DieID: 7924361434352
EthernetAddress: XXXXXXX
FirmwareVersion: iBoot-4076.30.43
FusingStatus: 3
HardwareModel: J86mAP
HardwarePlatform: s5l8960x
HasSiDP: true
HostAttached: true
InternationalMobileEquipmentIdentity: XXXXXXX
MLBSerialNumber: XXXXXXX
MobileEquipmentIdentifier: XXXXXXX
MobileSubscriberCountryCode: 
MobileSubscriberNetworkCode: 
ModelNumber: MGHV2
NonVolatileRAM: 
 auto-boot: dHJ1ZQ==
 backlight-level: MTU5OQ==
 boot-args: 
 bootdelay: MA==
 com.apple.System.tz0-size: MHg2MDAwMDA=
 oblit-begins: T2JsaXRUeXBlOiBPYmxpdGVyYXRlRGF0YVBhcnRpdGlvbi4gTm8gcmVhc29uIGdpdmVuLg==
 obliteration: aGFuZGxlX21lc3NhZ2U6IE9ibGl0ZXJhdGlvbiBDb21wbGV0ZQ==
PartitionType: GUID_partition_scheme
PasswordProtected: false
PkHash: 09pXQgM5cjY6TJJNOOzO//R5JuGKqjHElfshBbnxrhg=
ProductName: iPhone OS
ProductType: iPad4,8
ProductVersion: 11.2.2
ProductionSOC: true
ProtocolVersion: 2
ProximitySensorCalibration: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
RegionInfo: KH/A
SIMStatus: kCTSIMSupportSIMStatusNotInserted
SIMTrayStatus: kCTSIMSupportSIMTrayInsertedNoSIM
SerialNumber: XXXXXXX
SoftwareBehavior: GQIAAAAAAAAAAAAAAAAAAA==
SoftwareBundleVersion: 
SupportedDeviceFamilies[2]: 
 0: 1
 1: 2
TelephonyCapability: true
TimeIntervalSince1970: 1591150752.665899
TimeZone: Asia/Seoul
TimeZoneOffsetFromUTC: 32400.000000
TrustedHostAttached: true
UniqueChipID: XXXXXXX
UniqueDeviceID: XXXXXXX
UseRaptorCerts: true
Uses24HourClock: true
WiFiAddress: XXXXXXX
kCTPostponementInfoPRIVersion: 0.1.141
kCTPostponementInfoPRLName: 0
kCTPostponementInfoServiceProvisioningState: false
kCTPostponementStatus: kCTPostponementStatusActivated
```
